server:
  port: 9091

spring:
  profiles:
    active: local

mybatis:
  configuration:
    # snake case to camel case
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*SQL.xml